// swiftformat:disable all
// Generated by tuji-web/scripts/sync-study-choice-data.mjs. Do not edit.
struct StudyChoiceContractCase {
    let name: String
    let a: String
    let ag: String
    let b: String
    let bg: String
    let conflict: Bool
}
let studyChoiceContractCases: [StudyChoiceContractCase] = [
    .init(name: "washbasin spaces", a: "washbasin", ag: "洗手台", b: "wash basin", bg: "臉盆", conflict: true),
    .init(name: "case and width", a: "WASHBASIN", ag: "洗手台", b: "ｗａｓｈｂａｓｉｎ", bg: "臉盆", conflict: true),
    .init(name: "unicode hyphen", a: "wash-basin", ag: "洗手台", b: "wash‐basin", bg: "臉盆", conflict: true),
    .init(name: "synonym with different gloss", a: "sofa", ag: "沙發", b: "couch", bg: "長沙發", conflict: true),
    .init(name: "token subset", a: "knife", ag: "刀", b: "kitchen knife", bg: "菜刀", conflict: true),
    .init(name: "packed gloss", a: "pan", ag: "平底鍋 / 煎鍋", b: "skillet", bg: "煎鍋", conflict: true),
    .init(name: "CJK substring", a: "時計", ag: "時鐘", b: "腕時計", bg: "手錶", conflict: true),
    .init(name: "kana variant", a: "石鹸", ag: "香皂", b: "石けん", bg: "肥皂", conflict: true),
    .init(name: "distinct near spellings", a: "soap", ag: "肥皂", b: "soup", bg: "湯", conflict: false),
    .init(name: "distinct objects", a: "spoon", ag: "湯匙", b: "fork", bg: "叉子", conflict: false),
    .init(name: "keep Japanese long vowel", a: "ビル", ag: "大樓", b: "ビール", bg: "啤酒", conflict: false),
    .init(name: "width with long vowel", a: "ﾋﾞｰﾙ", ag: "啤酒", b: "ビール", bg: "麥酒", conflict: true),
    .init(name: "keep accents", a: "cafe", ag: "", b: "café", bg: "", conflict: false),
]
